language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-21
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26



script:
  - ./gradlew testDebugUnitTest
